version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: raw_listings
        identifier: raw_listings
        meta:
          dagster:
            asset_key: ["raw_listings"] # This metadata specifies the corresponding Dagster asset for this dbt source.
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4

          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"

      - name: raw_hosts
        identifier: raw_hosts
        meta:
          dagster:
            asset_key: ["raw_hosts"] # This metadata specifies the corresponding Dagster asset for this dbt source.

      - name: raw_reviews
        identifier: raw_reviews
        meta:
          dagster:
            asset_key: ["raw_reviews"] # This metadata specifies the corresponding Dagster asset for this dbt source.
        loaded_at_field: date
        freshness:
          warn_after: { count: 1, period: hour }
          error_after: { count: 24, period: hour }
